# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Yessica\UI\add_data.ui'
#
# Created: Tue Oct 16 13:08:54 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(617, 345)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.nameProgram_lineEdit = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nameProgram_lineEdit.setFont(font)
        self.nameProgram_lineEdit.setReadOnly(True)
        self.nameProgram_lineEdit.setObjectName(_fromUtf8("nameProgram_lineEdit"))
        self.horizontalLayout.addWidget(self.nameProgram_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.data_dateEdit = QtGui.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.data_dateEdit.setFont(font)
        self.data_dateEdit.setObjectName(_fromUtf8("data_dateEdit"))
        self.horizontalLayout_2.addWidget(self.data_dateEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.value_checkBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.value_checkBox.setFont(font)
        self.value_checkBox.setObjectName(_fromUtf8("value_checkBox"))
        self.horizontalLayout_4.addWidget(self.value_checkBox)
        self.data_value_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.data_value_spinBox.setEnabled(False)
        self.data_value_spinBox.setMinimum(0)
        self.data_value_spinBox.setMaximum(100000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_value_spinBox.sizePolicy().hasHeightForWidth())
        self.data_value_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.data_value_spinBox.setFont(font)
        self.data_value_spinBox.setObjectName(_fromUtf8("data_value_spinBox"))
        self.horizontalLayout_4.addWidget(self.data_value_spinBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comments_checkBox = QtGui.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comments_checkBox.setFont(font)
        self.comments_checkBox.setObjectName(_fromUtf8("comments_checkBox"))
        self.horizontalLayout_3.addWidget(self.comments_checkBox)
        self.comments_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.comments_lineEdit.setObjectName(_fromUtf8("comments_lineEdit"))
        self.horizontalLayout_3.addWidget(self.comments_lineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.accept_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.accept_button.setFont(font)
        self.accept_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.accept_button.setObjectName(_fromUtf8("accept_button"))
        self.horizontalLayout_6.addWidget(self.accept_button)
        self.quit_button = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.quit_button.setFont(font)
        self.quit_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quit_button.setObjectName(_fromUtf8("quit_button"))
        self.horizontalLayout_6.addWidget(self.quit_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.message_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.message_label.setFont(font)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout_5.addWidget(self.message_label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Program Name:", None))
        self.label_2.setText(_translate("MainWindow", "Data Date: ", None))
        self.value_checkBox.setText(_translate("MainWindow", "Value", None))
        self.comments_checkBox.setText(_translate("MainWindow", "Comments", None))
        self.accept_button.setText(_translate("MainWindow", "Accept", None))
        self.quit_button.setText(_translate("MainWindow", "Quit", None))
        self.message_label.setText(_translate("MainWindow", "Message", None))

