# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Yessica\UI\add_STO.ui'
#
# Created: Thu Oct 04 17:17:30 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(703, 198)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stoMathBehavior_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stoMathBehavior_comboBox.sizePolicy().hasHeightForWidth())
        self.stoMathBehavior_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stoMathBehavior_comboBox.setFont(font)
        self.stoMathBehavior_comboBox.setObjectName(_fromUtf8("stoMathBehavior_comboBox"))
        self.stoMathBehavior_comboBox.addItem(_fromUtf8(""))
        self.stoMathBehavior_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.stoMathBehavior_comboBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.stoBehavior_spinBox1 = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stoBehavior_spinBox1.setMaximum(1000000)
        self.stoBehavior_spinBox1.setFont(font)
        self.stoBehavior_spinBox1.setObjectName(_fromUtf8("stoBehavior_spinBox1"))
        self.horizontalLayout_2.addWidget(self.stoBehavior_spinBox1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.stoBehavior_spinBox2 = QtGui.QSpinBox(self.centralwidget)
        self.stoBehavior_spinBox2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stoBehavior_spinBox2.setMaximum(100000)
        self.stoBehavior_spinBox2.setFont(font)
        self.stoBehavior_spinBox2.setObjectName(_fromUtf8("stoBehavior_spinBox2"))
        self.horizontalLayout_2.addWidget(self.stoBehavior_spinBox2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.stoBehavior_spinBox3 = QtGui.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stoBehavior_spinBox3.setMaximum(100000)
        self.stoBehavior_spinBox3.setFont(font)
        self.stoBehavior_spinBox3.setObjectName(_fromUtf8("stoBehavior_spinBox3"))
        self.horizontalLayout.addWidget(self.stoBehavior_spinBox3)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.stoBehaviorTime_comboBox = QtGui.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stoBehaviorTime_comboBox.setFont(font)
        self.stoBehaviorTime_comboBox.setObjectName(_fromUtf8("stoBehaviorTime_comboBox"))
        self.stoBehaviorTime_comboBox.addItem(_fromUtf8(""))
        self.stoBehaviorTime_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.stoBehaviorTime_comboBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.mesage_add_sto = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesage_add_sto.sizePolicy().hasHeightForWidth())
        self.mesage_add_sto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mesage_add_sto.setFont(font)
        self.mesage_add_sto.setObjectName(_fromUtf8("mesage_add_sto"))
        self.horizontalLayout_4.addWidget(self.mesage_add_sto)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.addStoBehavior_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStoBehavior_pushButton.sizePolicy().hasHeightForWidth())
        self.addStoBehavior_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.addStoBehavior_pushButton.setFont(font)
        self.addStoBehavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addStoBehavior_pushButton.setObjectName(_fromUtf8("addStoBehavior_pushButton"))
        self.horizontalLayout_3.addWidget(self.addStoBehavior_pushButton)
        self.quit_pushButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.quit_pushButton.setFont(font)
        self.quit_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quit_pushButton.setObjectName(_fromUtf8("quit_pushButton"))
        self.horizontalLayout_3.addWidget(self.quit_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Add STO View", None))
        self.label_5.setText(_translate("MainWindow", "STO:", None))
        self.stoMathBehavior_comboBox.setItemText(0, _translate("MainWindow", "no more than", None))
        self.stoMathBehavior_comboBox.setItemText(1, _translate("MainWindow", "between", None))
        self.label.setText(_translate("MainWindow", "and", None))
        self.label_2.setText(_translate("MainWindow", "incidents per week  ", None))
        self.label_3.setText(_translate("MainWindow", "for", None))
        self.label_10.setText(_translate("MainWindow", "consecutives", None))
        self.stoBehaviorTime_comboBox.setItemText(0, _translate("MainWindow", "weeks", None))
        self.stoBehaviorTime_comboBox.setItemText(1, _translate("MainWindow", "months", None))
        self.mesage_add_sto.setText(_translate("MainWindow", "Message", None))
        self.addStoBehavior_pushButton.setText(_translate("MainWindow", "Add STO", None))
        self.quit_pushButton.setText(_translate("MainWindow", "Quit", None))

