# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Yessica\UI\edit_view.ui'
#
# Created: Tue Oct 16 13:50:25 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(811, 361)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.behaviors_widget_2 = QtGui.QWidget(self.centralwidget)
        self.behaviors_widget_2.setEnabled(True)
        self.behaviors_widget_2.setObjectName(_fromUtf8("behaviors_widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.behaviors_widget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.programName_lineEdit = QtGui.QLineEdit(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.programName_lineEdit.setFont(font)
        self.programName_lineEdit.setObjectName(_fromUtf8("programName_lineEdit"))
        self.horizontalLayout_12.addWidget(self.programName_lineEdit)
        self.name_edit = QtGui.QPushButton(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.name_edit.setFont(font)
        self.name_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.horizontalLayout_12.addWidget(self.name_edit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_12 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.baselineProgram_spinBox_2 = QtGui.QSpinBox(self.behaviors_widget_2)
        self.baselineProgram_spinBox_2.setMaximum(10000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselineProgram_spinBox_2.sizePolicy().hasHeightForWidth())
        self.baselineProgram_spinBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineProgram_spinBox_2.setFont(font)
        self.baselineProgram_spinBox_2.setObjectName(_fromUtf8("baselineProgram_spinBox_2"))
        self.horizontalLayout_13.addWidget(self.baselineProgram_spinBox_2)
        self.label_13 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.baselineProgram_comboBox = QtGui.QComboBox(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineProgram_comboBox.setFont(font)
        self.baselineProgram_comboBox.setObjectName(_fromUtf8("baselineProgram_comboBox"))
        self.baselineProgram_comboBox.addItem(_fromUtf8(""))
        self.baselineProgram_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.baselineProgram_comboBox)
        self.baselineProgram_dateEdit1 = QtGui.QDateEdit(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineProgram_dateEdit1.setFont(font)
        self.baselineProgram_dateEdit1.setObjectName(_fromUtf8("baselineProgram_dateEdit1"))
        self.horizontalLayout_13.addWidget(self.baselineProgram_dateEdit1)
        self.baselineProgram_checkBox_2 = QtGui.QCheckBox(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.baselineProgram_checkBox_2.setFont(font)
        self.baselineProgram_checkBox_2.setObjectName(_fromUtf8("baselineProgram_checkBox_2"))
        self.horizontalLayout_13.addWidget(self.baselineProgram_checkBox_2)
        self.baselineProgram_dateEdit2 = QtGui.QDateEdit(self.behaviors_widget_2)
        self.baselineProgram_dateEdit2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineProgram_dateEdit2.setFont(font)
        self.baselineProgram_dateEdit2.setObjectName(_fromUtf8("baselineProgram_dateEdit2"))
        self.horizontalLayout_13.addWidget(self.baselineProgram_dateEdit2)
        self.baseline_edit = QtGui.QPushButton(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baseline_edit.setFont(font)
        self.baseline_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.baseline_edit.setObjectName(_fromUtf8("baseline_edit"))
        self.horizontalLayout_13.addWidget(self.baseline_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.measureProgram_comboBox = QtGui.QComboBox(self.behaviors_widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureProgram_comboBox.sizePolicy().hasHeightForWidth())
        self.measureProgram_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.measureProgram_comboBox.setFont(font)
        self.measureProgram_comboBox.setObjectName(_fromUtf8("measureProgram_comboBox"))
        self.measureProgram_comboBox.addItem(_fromUtf8(""))
        self.measureProgram_comboBox.addItem(_fromUtf8(""))
        self.measureProgram_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_14.addWidget(self.measureProgram_comboBox)
        self.measure_edit = QtGui.QPushButton(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.measure_edit.setFont(font)
        self.measure_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.measure_edit.setObjectName(_fromUtf8("measure_edit"))
        self.horizontalLayout_14.addWidget(self.measure_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_15 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.ltoProgram_spinBox1 = QtGui.QSpinBox(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ltoProgram_spinBox1.setFont(font)
        self.ltoProgram_spinBox1.setMaximum(100000)
        self.ltoProgram_spinBox1.setObjectName(_fromUtf8("ltoProgram_spinBox1"))
        self.horizontalLayout_15.addWidget(self.ltoProgram_spinBox1)
        self.label_16 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.ltoProgram_spinBox2 = QtGui.QSpinBox(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ltoProgram_spinBox2.setMaximum(10000)
        self.ltoProgram_spinBox2.setFont(font)
        self.ltoProgram_spinBox2.setObjectName(_fromUtf8("ltoProgram_spinBox2"))
        self.horizontalLayout_15.addWidget(self.ltoProgram_spinBox2)
        self.label_17 = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.ltoProgram_comboBox = QtGui.QComboBox(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ltoProgram_comboBox.setFont(font)
        self.ltoProgram_comboBox.setObjectName(_fromUtf8("ltoProgram_comboBox"))
        self.ltoProgram_comboBox.addItem(_fromUtf8(""))
        self.ltoProgram_comboBox.addItem(_fromUtf8(""))
        self.ltoProgram_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.ltoProgram_comboBox)
        self.lto_edit = QtGui.QPushButton(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lto_edit.setFont(font)
        self.lto_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lto_edit.setObjectName(_fromUtf8("lto_edit"))
        self.horizontalLayout_15.addWidget(self.lto_edit)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.behaviors_widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.sto_comboBox = QtGui.QComboBox(self.behaviors_widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sto_comboBox.sizePolicy().hasHeightForWidth())
        self.sto_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sto_comboBox.setFont(font)
        self.sto_comboBox.setObjectName(_fromUtf8("sto_comboBox"))
        self.horizontalLayout_9.addWidget(self.sto_comboBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.sto_edit = QtGui.QPushButton(self.behaviors_widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sto_edit.sizePolicy().hasHeightForWidth())
        self.sto_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sto_edit.setFont(font)
        self.sto_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sto_edit.setObjectName(_fromUtf8("sto_edit"))
        self.horizontalLayout_9.addWidget(self.sto_edit)
        self.addStoProgram_pushButton = QtGui.QPushButton(self.behaviors_widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStoProgram_pushButton.sizePolicy().hasHeightForWidth())
        self.addStoProgram_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.addStoProgram_pushButton.setFont(font)
        self.addStoProgram_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addStoProgram_pushButton.setObjectName(_fromUtf8("addStoProgram_pushButton"))
        self.horizontalLayout_9.addWidget(self.addStoProgram_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.stoProgram_message = QtGui.QLabel(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stoProgram_message.setFont(font)
        self.stoProgram_message.setObjectName(_fromUtf8("stoProgram_message"))
        self.horizontalLayout_10.addWidget(self.stoProgram_message)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.cancelProgram_pushButton = QtGui.QPushButton(self.behaviors_widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancelProgram_pushButton.setFont(font)
        self.cancelProgram_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancelProgram_pushButton.setObjectName(_fromUtf8("cancelProgram_pushButton"))
        self.horizontalLayout_18.addWidget(self.cancelProgram_pushButton)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addWidget(self.behaviors_widget_2)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Program View", None))
        self.label_10.setText(_translate("MainWindow", "Program Name :", None))
        self.name_edit.setText(_translate("MainWindow", "Save Edit", None))
        self.label_12.setText(_translate("MainWindow", "Baseline:", None))
        self.label_13.setText(_translate("MainWindow", "per", None))
        self.baselineProgram_comboBox.setItemText(0, _translate("MainWindow", "Weeks", None))
        self.baselineProgram_comboBox.setItemText(1, _translate("MainWindow", "Months", None))
        self.baselineProgram_checkBox_2.setText(_translate("MainWindow", "to", None))
        self.baseline_edit.setText(_translate("MainWindow", "Save Edit", None))
        self.label_14.setText(_translate("MainWindow", "Measure Method:", None))
        self.measureProgram_comboBox.setItemText(0, _translate("MainWindow", "Time", None))
        self.measureProgram_comboBox.setItemText(1, _translate("MainWindow", "% of Opportunities", None))
        self.measureProgram_comboBox.setItemText(2, _translate("MainWindow", "Frequency", None))
        self.measure_edit.setText(_translate("MainWindow", "Save Edit", None))
        self.label_15.setText(_translate("MainWindow", "LTO:", None))
        self.label_16.setText(_translate("MainWindow", "per", None))
        self.label_17.setText(_translate("MainWindow", "consecutive", None))
        self.ltoProgram_comboBox.setItemText(0, _translate("MainWindow", "Days", None))
        self.ltoProgram_comboBox.setItemText(1, _translate("MainWindow", "Weeks", None))
        self.ltoProgram_comboBox.setItemText(2, _translate("MainWindow", "Months", None))
        self.lto_edit.setText(_translate("MainWindow", "Save Edit", None))
        self.label_5.setText(_translate("MainWindow", "STO:", None))
        self.sto_edit.setText(_translate("MainWindow", "Edit STO", None))
        self.addStoProgram_pushButton.setText(_translate("MainWindow", "Add STO", None))
        self.stoProgram_message.setText(_translate("MainWindow", "Message", None))
        self.cancelProgram_pushButton.setText(_translate("MainWindow", "Quit", None))

