# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Yessica\UI\newBehavior.ui'
#
# Created: Wed Oct 17 17:16:27 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(703, 339)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.behaviors_widget = QtGui.QWidget(self.centralwidget)
        self.behaviors_widget.setEnabled(True)
        self.behaviors_widget.setObjectName(_fromUtf8("behaviors_widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.behaviors_widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.behaviorName_lineEdit = QtGui.QLineEdit(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.behaviorName_lineEdit.setFont(font)
        self.behaviorName_lineEdit.setObjectName(_fromUtf8("behaviorName_lineEdit"))
        self.horizontalLayout_5.addWidget(self.behaviorName_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.baselineBehavior_spinBox = QtGui.QSpinBox(self.behaviors_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselineBehavior_spinBox.sizePolicy().hasHeightForWidth())
        self.baselineBehavior_spinBox.setMaximum(100000)
        self.baselineBehavior_spinBox.setSizePolicy(sizePolicy)
        self.baselineBehavior_spinBox.setObjectName(_fromUtf8("baselineBehavior_spinBox"))
        self.horizontalLayout_6.addWidget(self.baselineBehavior_spinBox)
        self.label_7 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.baselineBehavior_comboBox = QtGui.QComboBox(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineBehavior_comboBox.setFont(font)
        self.baselineBehavior_comboBox.setObjectName(_fromUtf8("baselineBehavior_comboBox"))
        self.baselineBehavior_comboBox.addItem(_fromUtf8(""))
        self.baselineBehavior_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.baselineBehavior_comboBox)
        self.baselineBehavior_dateEdit1 = QtGui.QDateEdit(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineBehavior_dateEdit1.setFont(font)
        self.baselineBehavior_dateEdit1.setObjectName(_fromUtf8("baselineBehavior_dateEdit1"))
        self.horizontalLayout_6.addWidget(self.baselineBehavior_dateEdit1)
        self.baselineBehavior_checkBox = QtGui.QCheckBox(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.baselineBehavior_checkBox.setFont(font)
        self.baselineBehavior_checkBox.setObjectName(_fromUtf8("baselineBehavior_checkBox"))
        self.horizontalLayout_6.addWidget(self.baselineBehavior_checkBox)
        self.baselineBehavior_dateEdit2 = QtGui.QDateEdit(self.behaviors_widget)
        self.baselineBehavior_dateEdit2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.baselineBehavior_dateEdit2.setFont(font)
        self.baselineBehavior_dateEdit2.setObjectName(_fromUtf8("baselineBehavior_dateEdit2"))
        self.horizontalLayout_6.addWidget(self.baselineBehavior_dateEdit2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_11 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.measureBehavior_comboBox = QtGui.QComboBox(self.behaviors_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureBehavior_comboBox.sizePolicy().hasHeightForWidth())
        self.measureBehavior_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.measureBehavior_comboBox.setFont(font)
        self.measureBehavior_comboBox.setObjectName(_fromUtf8("measureBehavior_comboBox"))
        self.measureBehavior_comboBox.addItem(_fromUtf8(""))
        self.measureBehavior_comboBox.addItem(_fromUtf8(""))
        self.measureBehavior_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.measureBehavior_comboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.ltoBehavior_spinBox1 = QtGui.QSpinBox(self.behaviors_widget)
        self.ltoBehavior_spinBox1.setMaximum(10000)
        self.ltoBehavior_spinBox1.setObjectName(_fromUtf8("ltoBehavior_spinBox1"))
        self.horizontalLayout_8.addWidget(self.ltoBehavior_spinBox1)
        self.label_8 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.ltoBehavior_spinBox2 = QtGui.QSpinBox(self.behaviors_widget)
        self.ltoBehavior_spinBox2.setMaximum(100000)
        self.ltoBehavior_spinBox2.setObjectName(_fromUtf8("ltoBehavior_spinBox2"))
        self.horizontalLayout_8.addWidget(self.ltoBehavior_spinBox2)
        self.label_9 = QtGui.QLabel(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.ltoBehavior_comboBox = QtGui.QComboBox(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ltoBehavior_comboBox.setFont(font)
        self.ltoBehavior_comboBox.setObjectName(_fromUtf8("ltoBehavior_comboBox"))
        self.ltoBehavior_comboBox.addItem(_fromUtf8(""))
        self.ltoBehavior_comboBox.addItem(_fromUtf8(""))
        self.ltoBehavior_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.ltoBehavior_comboBox)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.behaviors_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.sto_comboBox = QtGui.QComboBox(self.behaviors_widget)
        self.sto_comboBox.setObjectName(_fromUtf8("sto_comboBox"))
        self.horizontalLayout_9.addWidget(self.sto_comboBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.addStoBehavior_pushButton = QtGui.QPushButton(self.behaviors_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStoBehavior_pushButton.sizePolicy().hasHeightForWidth())
        self.addStoBehavior_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.addStoBehavior_pushButton.setFont(font)
        self.addStoBehavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addStoBehavior_pushButton.setObjectName(_fromUtf8("addStoBehavior_pushButton"))
        self.horizontalLayout_9.addWidget(self.addStoBehavior_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.acceptBehavior_pushButton = QtGui.QPushButton(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.acceptBehavior_pushButton.setFont(font)
        self.acceptBehavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.acceptBehavior_pushButton.setObjectName(_fromUtf8("acceptBehavior_pushButton"))
        self.horizontalLayout_11.addWidget(self.acceptBehavior_pushButton)
        self.cancelBehavior_pushButton = QtGui.QPushButton(self.behaviors_widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancelBehavior_pushButton.setFont(font)
        self.cancelBehavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancelBehavior_pushButton.setObjectName(_fromUtf8("cancelBehavior_pushButton"))
        self.horizontalLayout_11.addWidget(self.cancelBehavior_pushButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.stoBehavior_message = QtGui.QLabel(self.behaviors_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stoBehavior_message.sizePolicy().hasHeightForWidth())
        self.stoBehavior_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stoBehavior_message.setFont(font)
        self.stoBehavior_message.setObjectName(_fromUtf8("stoBehavior_message"))
        self.horizontalLayout_10.addWidget(self.stoBehavior_message)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.behaviors_widget)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Behavior View", None))
        self.label_3.setText(_translate("MainWindow", "Maladaptive Behavior Name :", None))
        self.label_4.setText(_translate("MainWindow", "Baseline:", None))
        self.label_7.setText(_translate("MainWindow", "per", None))
        self.baselineBehavior_comboBox.setItemText(0, _translate("MainWindow", "Weeks", None))
        self.baselineBehavior_comboBox.setItemText(1, _translate("MainWindow", "Months", None))
        self.baselineBehavior_checkBox.setText(_translate("MainWindow", "to", None))
        self.label_11.setText(_translate("MainWindow", "Measure Method:", None))
        self.measureBehavior_comboBox.setItemText(0, _translate("MainWindow", "Time", None))
        self.measureBehavior_comboBox.setItemText(1, _translate("MainWindow", "%", None))
        self.measureBehavior_comboBox.setItemText(2, _translate("MainWindow", "Frequency", None))
        self.label_6.setText(_translate("MainWindow", "LTO:", None))
        self.label_8.setText(_translate("MainWindow", "per", None))
        self.label_9.setText(_translate("MainWindow", "consecutive", None))
        self.ltoBehavior_comboBox.setItemText(0, _translate("MainWindow", "Days", None))
        self.ltoBehavior_comboBox.setItemText(1, _translate("MainWindow", "Weeks", None))
        self.ltoBehavior_comboBox.setItemText(2, _translate("MainWindow", "Months", None))
        self.label_5.setText(_translate("MainWindow", "STO:", None))
        self.addStoBehavior_pushButton.setText(_translate("MainWindow", "Add STO", None))
        self.acceptBehavior_pushButton.setText(_translate("MainWindow", "Accept", None))
        self.cancelBehavior_pushButton.setText(_translate("MainWindow", "Quit", None))
        self.stoBehavior_message.setText(_translate("MainWindow", "Message", None))

