# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Yessica\UI\show_kid.ui'
#
# Created: Wed Nov 28 14:56:32 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

import os

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QPixmap

from resources.button_class import PicButton

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 452)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.kidName_lineEdit = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.kidName_lineEdit.setFont(font)
        self.kidName_lineEdit.setReadOnly(False)
        self.kidName_lineEdit.setObjectName(_fromUtf8("kidName_lineEdit"))
        self.horizontalLayout.addWidget(self.kidName_lineEdit)

        # self.edit_name = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.edit_name.sizePolicy().hasHeightForWidth())
        # self.edit_name.setSizePolicy(sizePolicy)
        # self.edit_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.edit_name.setFont(font)
        # self.edit_name.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.edit_name.setIconSize(QtCore.QSize(20, 20))
        # self.edit_name.setObjectName(_fromUtf8("edit_name"))
        self.edit_name = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Save-128.png")))
        self.edit_name.setToolTip("Save")
        self.horizontalLayout.addWidget(self.edit_name)

        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_6.addWidget(self.lineEdit)

        # self.edit_last_name = QtGui.QPushButton(self.centralwidget)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.edit_last_name.setFont(font)
        # self.edit_last_name.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.edit_last_name.setObjectName(_fromUtf8("edit_last_name"))
        self.edit_last_name = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Save-128.png")))
        self.edit_last_name.setToolTip("Save")
        self.horizontalLayout_6.addWidget(self.edit_last_name)

        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.kidAge_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.kidAge_spinBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kidAge_spinBox.sizePolicy().hasHeightForWidth())
        self.kidAge_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.kidAge_spinBox.setFont(font)
        self.kidAge_spinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.kidAge_spinBox.setReadOnly(False)
        self.kidAge_spinBox.setMaximum(200)
        self.kidAge_spinBox.setObjectName(_fromUtf8("kidAge_spinBox"))
        self.horizontalLayout_4.addWidget(self.kidAge_spinBox)

        # self.edit_age = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.edit_age.sizePolicy().hasHeightForWidth())
        # self.edit_age.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.edit_age.setFont(font)
        # self.edit_age.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.edit_age.setObjectName(_fromUtf8("edit_age"))
        self.edit_age = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Save-128.png")))
        self.edit_age.setToolTip("Save")
        self.horizontalLayout_4.addWidget(self.edit_age)

        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.medicaidID_line_edit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medicaidID_line_edit.sizePolicy().hasHeightForWidth())
        self.medicaidID_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.medicaidID_line_edit.setFont(font)
        self.medicaidID_line_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.medicaidID_line_edit.setReadOnly(True)
        self.medicaidID_line_edit.setObjectName(_fromUtf8("medicaidID_line_edit"))
        self.horizontalLayout_4.addWidget(self.medicaidID_line_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_2)

        # self.edit_analyst = QtGui.QPushButton(self.centralwidget)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.edit_analyst.setFont(font)
        # self.edit_analyst.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.edit_analyst.setObjectName(_fromUtf8("edit_analyst"))
        self.edit_analyst = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Save-128.png")))
        self.edit_analyst.setToolTip("Save")
        self.horizontalLayout_8.addWidget(self.edit_analyst)

        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))

        # ESTO LO AGREGUE YO
        self.addBehavior = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Plus-128.png")))
        self.addBehavior.setToolTip("Add Behavior")
        self.horizontalLayout_3.addWidget(self.addBehavior)

        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)

        # self.behavior_view_data__pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.behavior_view_data__pushButton.sizePolicy().hasHeightForWidth())
        # self.behavior_view_data__pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.behavior_view_data__pushButton.setFont(font)
        # self.behavior_view_data__pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.behavior_view_data__pushButton.setObjectName(_fromUtf8("behavior_view_data__pushButton"))
        # self.horizontalLayout_3.addWidget(self.behavior_view_data__pushButton)

        # self.editBehavior_pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.editBehavior_pushButton.sizePolicy().hasHeightForWidth())
        # self.editBehavior_pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.editBehavior_pushButton.setFont(font)
        # self.editBehavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.editBehavior_pushButton.setObjectName(_fromUtf8("editBehavior_pushButton"))
        self.editBehavior_pushButton = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\clipboard-edit-128(2).png")))
        self.editBehavior_pushButton.setToolTip("Edit")
        self.horizontalLayout_3.addWidget(self.editBehavior_pushButton)

        # self.delete_behavior_pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.delete_behavior_pushButton.sizePolicy().hasHeightForWidth())
        # self.delete_behavior_pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.delete_behavior_pushButton.setFont(font)
        # self.delete_behavior_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.delete_behavior_pushButton.setObjectName(_fromUtf8("delete_behavior_pushButton"))
        self.delete_behavior_pushButton = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\edit-delete-128.png")))
        self.delete_behavior_pushButton.setToolTip("Delete")
        self.horizontalLayout_3.addWidget(self.delete_behavior_pushButton)

        # self.addBehaviors_Button = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.addBehaviors_Button.sizePolicy().hasHeightForWidth())
        # self.addBehaviors_Button.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.addBehaviors_Button.setFont(font)
        # self.addBehaviors_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.addBehaviors_Button.setObjectName(_fromUtf8("addBehaviors_Button"))
        self.addDataBehaviors_Button = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\add-128(2).png")))
        self.addDataBehaviors_Button.setToolTip("Add Data")
        self.horizontalLayout_3.addWidget(self.addDataBehaviors_Button)

        self.viewGrahics_behavior = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\view-graphics.png")))
        self.viewGrahics_behavior.setToolTip("View Graphics")
        self.horizontalLayout_3.addWidget(self.viewGrahics_behavior)

        spacerItem6 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))

        # ESTO LO PUSE YO
        self.addProgram = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\Plus-128.png")))
        self.addProgram.setToolTip("Add Program")
        self.horizontalLayout_2.addWidget(self.addProgram)

        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)

        # self.program_view_data__pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.program_view_data__pushButton.sizePolicy().hasHeightForWidth())
        # self.program_view_data__pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.program_view_data__pushButton.setFont(font)
        # self.program_view_data__pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.program_view_data__pushButton.setObjectName(_fromUtf8("program_view_data__pushButton"))
        # self.horizontalLayout_2.addWidget(self.program_view_data__pushButton)

        # self.editProgram_pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.editProgram_pushButton.sizePolicy().hasHeightForWidth())
        # self.editProgram_pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.editProgram_pushButton.setFont(font)
        # self.editProgram_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.editProgram_pushButton.setObjectName(_fromUtf8("editProgram_pushButton"))
        self.editProgram_pushButton = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\clipboard-edit-128(2).png")))
        self.editProgram_pushButton.setToolTip("Edit")
        self.horizontalLayout_2.addWidget(self.editProgram_pushButton)

        # self.delete_program_pushButton = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.delete_program_pushButton.sizePolicy().hasHeightForWidth())
        # self.delete_program_pushButton.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.delete_program_pushButton.setFont(font)
        # self.delete_program_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.delete_program_pushButton.setObjectName(_fromUtf8("delete_program_pushButton"))
        self.delete_program_pushButton = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\edit-delete-128.png")))
        self.delete_program_pushButton.setToolTip("Delete")
        self.horizontalLayout_2.addWidget(self.delete_program_pushButton)

        # self.addProgram_Button = QtGui.QPushButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.addProgram_Button.sizePolicy().hasHeightForWidth())
        # self.addProgram_Button.setSizePolicy(sizePolicy)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.addProgram_Button.setFont(font)
        # self.addProgram_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.addProgram_Button.setObjectName(_fromUtf8("addProgram_Button"))
        self.addDataProgram_Button = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\add-128(2).png")))
        self.addDataProgram_Button.setToolTip("Add Data")
        self.horizontalLayout_2.addWidget(self.addDataProgram_Button)

        self.viewGrahics_program = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\view-graphics.png")))
        self.viewGrahics_program.setToolTip("View Graphics")
        self.horizontalLayout_2.addWidget(self.viewGrahics_program)

        spacerItem8 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)

        self.export_monthly_button = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\add_blue-128.png")))

        self.export_monthly_button.setToolTip("Create Monthly")
        self.horizontalLayout_5.addWidget(self.export_monthly_button)

        # self.finish_pushButton = QtGui.QPushButton(self.centralwidget)
        # font = QtGui.QFont()
        # font.setPointSize(9)
        # self.finish_pushButton.setFont(font)
        # self.finish_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        # self.finish_pushButton.setObjectName(_fromUtf8("finish_pushButton"))
        self.finish_pushButton = PicButton(QPixmap(os.path.join(os.getcwd(), "icon\\cancelar.png")))

        self.finish_pushButton.setToolTip("Back")
        self.horizontalLayout_5.addWidget(self.finish_pushButton)

        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.message_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.message_label.setFont(font)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.horizontalLayout_7.addWidget(self.message_label)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Data Kid View", None))
        self.label.setText(_translate("MainWindow", "Name:", None))
        self.edit_name.setText(_translate("MainWindow", "Save Edit", None))
        self.label_5.setText(_translate("MainWindow", "Last Name:", None))
        self.edit_last_name.setText(_translate("MainWindow", "Save Edit", None))
        self.label_2.setText(_translate("MainWindow", "Age:", None))
        self.edit_age.setText(_translate("MainWindow", "Save Edit", None))
        self.label_6.setText(_translate("MainWindow", "Medicaid ID:", None))
        self.label_7.setText(_translate("MainWindow", "Analyst:", None))
        self.edit_analyst.setText(_translate("MainWindow", "Save Edit", None))
        self.label_3.setText(_translate("MainWindow", "Maladaptive Behavior:", None))
        # self.behavior_view_data__pushButton.setText(_translate("MainWindow", "View Data", None))
        # self.editBehavior_pushButton.setText(_translate("MainWindow", "Edit", None))
        # self.delete_behavior_pushButton.setText(_translate("MainWindow", "Delete", None))
        # self.addBehaviors_Button.setText(_translate("MainWindow", "Add", None))
        self.label_4.setText(_translate("MainWindow", "Programs:", None))
        # self.program_view_data__pushButton.setText(_translate("MainWindow", "View Data", None))
        # self.editProgram_pushButton.setText(_translate("MainWindow", "Edit", None))
        # self.delete_program_pushButton.setText(_translate("MainWindow", "Delete", None))
        # self.addProgram_Button.setText(_translate("MainWindow", "Add", None))
        self.finish_pushButton.setText(_translate("MainWindow", "Quit", None))
        self.message_label.setText(_translate("MainWindow", "Message", None))

